FROM node:20-alpine AS build
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_API_BASE_URL
ARG VITE_KEYCLOAK_URL
ARG VITE_KEYCLOAK_REALM
ARG VITE_KEYCLOAK_CLIENT_ID

# White-label / custom brand inputs (optional — defaults in brand.config.ts)
ARG VITE_BRAND_NAME
ARG VITE_BRAND_TAGLINE
ARG VITE_BRAND_LOGO_URL
ARG VITE_BRAND_SIDEBAR_TAGLINE
ARG VITE_BRAND_COLOR_PRIMARY
ARG VITE_BRAND_COLOR_SECONDARY

ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_KEYCLOAK_URL=$VITE_KEYCLOAK_URL
ENV VITE_KEYCLOAK_REALM=$VITE_KEYCLOAK_REALM
ENV VITE_KEYCLOAK_CLIENT_ID=$VITE_KEYCLOAK_CLIENT_ID
ENV VITE_BRAND_NAME=$VITE_BRAND_NAME
ENV VITE_BRAND_TAGLINE=$VITE_BRAND_TAGLINE
ENV VITE_BRAND_LOGO_URL=$VITE_BRAND_LOGO_URL
ENV VITE_BRAND_SIDEBAR_TAGLINE=$VITE_BRAND_SIDEBAR_TAGLINE
ENV VITE_BRAND_COLOR_PRIMARY=$VITE_BRAND_COLOR_PRIMARY
ENV VITE_BRAND_COLOR_SECONDARY=$VITE_BRAND_COLOR_SECONDARY

RUN npm run build

FROM nginx:1.27-alpine

COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
